latency-wait: 6000
keep-going: True
keep-incomplete: True
rerun-incomplete: True
rerun-triggers: 
  - mtime
  - params
  - input
printshellcmds: True
use-conda: True
use-envmodules: True
use-singularity: True

