channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - biopython 
  - matplotlib 
  - numpy == 1.26.4
  - pandas 
  - pysam
  - python >= 3.10
  - python-intervaltree
  - requests
  - scipy
  - python-isal
